---
name: Upload Zip Exported From Webflow To Azure Blob Storage
on:
  workflow_dispatch:
    
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: unzip ${{ inputs.projectname }}.webflow.zip -d unzipped
      - uses: bacongobbler/azure-blob-storage-upload@874139251d8ba621ed4080cce9b5ebd0fcc019a2
        with:
          source_dir: 'unzipped'
          container_name: '$web'
          connection_string: ${{ secrets.ConnectionString }}
          sync: 'true'