---
name: Upload Zip Exported From Webflow To Cloudflare R2 Storage
on:
    workflow_call:
        inputs:
            project_name:
                description: "Name of the webflow project so that '<project_name>.webflow.zip' matches the name of the webflow export."
                type: string
                required: true
            static_folder:
                description: "Name of the folder with static files which should be added."
                type: string
                required: false
            replacement_file:
                description: "YAML file specifying edits to make to the webflow exported files."
                type: string
                required: false
            cache_control:
                description: "Cache control string. Default: 'max-age=21600'"
                type: string
                default: "max-age=21600"
                required: false

        secrets:
            access_key:
                description: "Access key for the R2 storage account."
                required: true
            secret_access_key:
                description: "Access key for the R2 storage account."
                required: true
            r2_endpoint_url:
                description: "Endpoint url for R2 upload. (https://<accountid>.r2.cloudflarestorage.com)"
                required: true
            r2_bucket:
                description: "Bucket name"
                required: true

jobs:
    upload:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
                with:
                    lfs: 'true'
            -   run: unzip ${{ inputs.project_name }}.webflow.zip -d unzipped
            -   name: replace
                if: ${{ inputs.replacement_file != ''}}
                uses: "./actions/search-replace-action"
                with:
                    replacement_file: ${{ inputs.replacement_file }}
                    dir: "unzipped"
            -   name: Merge Webflow with other required (static) files
                if: ${{ inputs.static_folder != ''}}
                run: cp -R -a ${{ inputs.static_folder }}/. unzipped/
            -   name: Upload to R2 storage
                run: |
                    aws s3 sync unzipped s3://"${{ secrets.r2_bucket }}" --endpoint-url "${{ secrets.r2_endpoint_url }}" --cache-control "${{ inputs.cache_control }}" --delete
                env:
                    AWS_ACCESS_KEY_ID: ${{ secrets.access_key }}
                    AWS_SECRET_ACCESS_KEY: ${{ secrets.secret_access_key }}
                    AWS_DEFAULT_REGION: auto # set default region: not actually used, as we set endpoint-url, but without, aws s3 cli fails.
